# Generated by Django 4.2.6 on 2023-10-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_specialist_medicaldoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldepartment',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
