# Generated by Django 4.2.7 on 2023-11-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_medicaldepartment_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicaldoctor',
            unique_together={('name', 'department')},
        ),
    ]
