# Generated by Django 4.2.7 on 2023-11-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_medicaldoctor_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldoctor',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
