# Generated by Django 4.2.7 on 2023-11-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_medicaldoctor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldoctor',
            name='hospital',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
